# https://prettier.io/docs/configuration
trailingComma: "es5"
tabWidth: 2
semi: false
singleQuote: true
overrides:
  - files: "*.html"
    options:
      printWidth: 400
      htmlWhitespaceSensitivity: "ignore"

