[project]
name = "github-trending-feeds"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "beautifulsoup4==4.15.0",
  "click==8.5.0",
  "dateparser==1.4.2",
  "lxml>=5.4.0",
  "requests==2.34.2",
  "types-lxml>=2025.3.30",
]

[dependency-groups]
dev = ["ruff>=0.14.10"]
