name: scrape_weekly_trending
on:
  # Cron job
  schedule:
    # every Monday
    - cron: '0 12 * * 1' # UTC 12:00 = JST 21:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape_github_trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pip install 
        run: pip install -r ./requirements.txt

      - name: scraping trending
        run: ./scripts/scrape_weekly_trending.sh

      - name: copy atoms
        run: |
          d=$(date -I)

          for atom in $(ls ./docs/feeds/*/weekly.atom); do
            mkdir -p "$(dirname $atom)/weekly"
            cp "${atom}" "$(dirname $atom)/weekly/weekly-${d}.atom"
          done
          
      - name: Create new commit
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git pull
          git add ./docs/feeds/
          git commit -m "add/update the file about weekly trending of github at $(date '+%Y-%m-%dT%H:%M:%S%z')" 
          git push
  