name: scrape_daily_trending
on:
  # Cron job
  schedule:
    # - cron: '0 11 * * *' # UTC 11:00 = JST 20:00
    # - cron: '0 13 * * *' # UTC 13:00 = JST 22:00
    - cron: '0 15 * * *' # UTC 15:00 = JST 24:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape_github_trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pip install 
        run: pip install -r ./requirements.txt

      - name: scraping trending
        run: ./scripts/scrape_daily_trending.sh

      - name: copy atoms
        run: |
          d=$(date -I)

          for atom in $(ls ./docs/feeds/*/daily.atom); do
            mkdir -p "$(dirname $atom)/daily"
            cp "${atom}" "$(dirname $atom)/daily/daily-${d}.atom"
          done
          
      - name: Create new commit
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git pull
          git add ./docs/feeds/
          git commit -m "add/update the file about daily trending of github at $(date '+%Y-%m-%dT%H:%M:%S%z')" 
          git push
  