name: scrape_trending_monthly
on:
  # Cron job
  schedule:
    # 1st day every month
    # - cron: "0 11 1 * *" # UTC 11:00 = JST 20:00
    # - cron: "0 12 1 * *" # UTC 12:00 = JST 21:00
    # - cron: "0 13 1 * *" # UTC 13:00 = JST 22:00
    # - cron: "0 14 1 * *" # UTC 14:00 = JST 23:00
    # - cron: "0 15 1 * *" # UTC 15:00 = JST 24:00 (00:00)
    # - cron: "0 16 1 * *" # UTC 16:00 = JST 25:00 (01:00)
    - cron: "0 17 1 * *" # UTC 17:00 = JST 26:00 (02:00)
    # - cron: "0 18 1 * *" # UTC 18:00 = JST 27:00 (03:00)
    # - cron: "0 19 1 * *" # UTC 19:00 = JST 28:00 (04:00)
    # - cron: "0 20 1 * *" # UTC 20:00 = JST 29:00 (05:00)
    # - cron: "0 21 1 * *" # UTC 21:00 = JST 30:00 (06:00)
    # - cron: "0 22 1 * *" # UTC 22:00 = JST 31:00 (07:00)
    # - cron: "0 23 1 * *" # UTC 23:00 = JST 32:00 (08:00)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      skip_scrape:
        description: "Scrape ジョブを飛ばす？"
        type: boolean # UI はトグルスイッチになる
        default: false # 未指定なら通常実行

jobs:
  scrape_github_trending:
    if: |
      ( github.event_name != 'workflow_dispatch' ) ||
      ( github.event_name == 'workflow_dispatch' && !fromJson(github.event.inputs.skip_scrape || 'false') )
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Checkout github-trending-feeds
        uses: actions/checkout@v4
        with:
          path: github-trending-feeds
      - name: Checkout github-trending-feeds-data
        uses: actions/checkout@v4
        with:
          repository: aazw/github-trending-feeds-data
          token: ${{ secrets.TOKEN_TO_PUSH_TO_GITHUB_TRENDING_FEEDS_DATA }}
          path: github-trending-feeds-data
      - name: Install packages
        working-directory: github-trending-feeds
        run: uv sync --link-mode=copy
      - name: Scrape trending
        working-directory: github-trending-feeds
        run: ./scripts/scrape_trending_monthly.sh
      - name: Copy atoms with date
        working-directory: github-trending-feeds
        run: |
          d=$(date -I)

          for atom in $(ls ./docs/feeds/*/monthly.atom); do
            mkdir -p "$(dirname $atom)/monthly"
            cp "${atom}" "$(dirname $atom)/monthly/monthly-${d}.atom"
          done
      - name: Copy to data repo
        run: cp -r github-trending-feeds/docs/feeds/* github-trending-feeds-data/docs/feeds/
      - name: Create new commit
        working-directory: github-trending-feeds-data
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add ./docs/feeds/
          git commit -m "add/update the file about monthly trending of github at $(date '+%Y-%m-%dT%H:%M:%S%z')" 
          git push
