name: scrape_monthly_trending
on:
  # Cron job
  schedule:
    # 1st day every month
    - cron: '0 13 1 * *' # UTC 13:00 = JST 22:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape_github_trending:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: pip install 
        run: pip install -r ./requirements.txt

      - name: scraping trending
        run: ./scripts/scrape_monthly_trending.sh

      - name: copy atoms
        run: |
          d=$(date -I)

          for atom in $(ls ./docs/feeds/*/monthly.atom); do
            mkdir -p "$(dirname $atom)/monthly"
            cp "${atom}" "$(dirname $atom)/monthly/monthly-${d}.atom"
          done
          
      - name: Create new commit
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git pull
          git add ./docs/feeds/
          git commit -m "add/update the file about monthly trending of github at $(date '+%Y-%m-%dT%H:%M:%S%z')" 
          git push
  